travis:
  secure:
    BINSTAR_TOKEN: ZxY3+9ZCX1poGt2YGkiMiSjKU17huZSm0fZi1LdXKVFycLYhKz58UGcLloP4zqIVPtn7ErsMummjlGJN+P3dCmLhPsFNdBoiuQEFFoPDjC+4IkjmroOz55bgnxZDxmu0ywSIGTj9FK/ykOtVMnH+UZGjBnaGncexnyWkXCmtF2CDOVaa0jsrwpA1U/6TDo5aWtygxy8dfxu/RFdfV/aog3M6em62PvSpMxDHSYIhu0zLA8GPWJZwAqfnlnGkjimQL/d5wKjKfVspHp72MDV2o4/uXJAcDFCUXLiC+5PFUmRSfxrWHtfGfU+qlR/M3vghMAc/6Kw3tH5UrlivBqK/AiF7h9VxEKvYYmsVntN2EVWsel/hSH3kdYQ5JDOqs1bIDcMH4xbElgjbiOdgGCQ9bcjkFvdLBMhn+Lj4MR40hpJwFiAKUn3kDLZF0pI+nsE3fAetA47yodqiYuZhIPA/QadqwaQZNC077zJyisP0Ez5cD+O165hIvhOIrZO5bH4JoRz/oEayjuBRrkJ+tv7UPXpSvGufAGpjCwqTN7V0Kc9F0FFUt/UdK8ZKSc6JRSuYfPXZU91FfORtcOXudOefmggcUwr6LqPgyoNbVxzLS9x6JBydZCgxp0wy7UcF1pOM0UL5M2i3VvJ0PpzctZTMaR16IB0INIIf9mkXEj4aHz8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
